import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "../styles/_reset-css.css";
import "../styles/typing-theme.css";
import "./globals.css";
import { LayoutProvider } from "@/contexts/layoutStates";
import { CreateBoardProvider } from "@/contexts/createBoardStates";
import { NotifyProvider } from "@/contexts/notifyStates";
import { TypingThemeProvider } from "@/contexts/typingThemeStates";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust based on what you need
  variable: "--font-roboto-mono", // optional, for use in CSS
  display: "swap", // optional for better UX
});

export const metadata: Metadata = {
  title: "My Memories",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/memories-metadata-icon.png", // default favicon
    shortcut: "/icons/memories-metadata-icon.png", // browser shortcut icon
    apple: "/apple-touch-icon.png", // for iOS devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`fixed inset-0 text-primaryBlack`}>
        <CreateBoardProvider>
          <NotifyProvider>
            <TypingThemeProvider>
              <LayoutProvider>
                <div id="myportal" />
                {children}
              </LayoutProvider>
            </TypingThemeProvider>
          </NotifyProvider>
        </CreateBoardProvider>
      </body>
    </html>
  );
}
